{% set name = "PETPVC" %}
{% set version = "1.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UCL/PETPVC/archive/v{{ version }}.tar.gz
  sha256: f9339a73a80ac6fdacac4543b8ff9ae1b76344dd40cdf7e87337d0484576c245

build:
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - libitk-devel
  run:
    - libitk

test:
  commands:
    - petpvc

about:
  home: https://github.com/UCL/PETPVC
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Toolbox for partial volume correction (PVC) in positron emission tomography (PET)

extra:
  recipe-maintainers:
    - ghisvail
